// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/loan/v1/loan.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LoanStatus merupakam status dari sebuah pinjaman
type LoanStatus int32

const (
	// nilai default
	LoanStatus_LOAN_STATUS_UNSPECIFIED LoanStatus = 0
	// pinjaman baru dibuat dan menunggu persetujuan
	LoanStatus_LOAN_STATUS_PENDING LoanStatus = 1
	// pinjaman telah disetujui oleh policy yang berwenang (laz)
	LoanStatus_LOAN_STATUS_APPROVED LoanStatus = 2
	// dana sudah dicairkan ke borrower
	LoanStatus_LOAN_STATUS_DISBURSED LoanStatus = 3
	// sisa dana telah dibayarkan
	LoanStatus_LOAN_STATUS_REPAID LoanStatus = 4
	// pinjaman ditolak oleh policy yang berwenang (laz)
	LoanStatus_LOAN_STATUS_REJECTED LoanStatus = 5
	// pinjaman dibatalkan sebelum pencairan
	LoanStatus_LOAN_STATUS_CANCELLED LoanStatus = 6
)

var LoanStatus_name = map[int32]string{
	0: "LOAN_STATUS_UNSPECIFIED",
	1: "LOAN_STATUS_PENDING",
	2: "LOAN_STATUS_APPROVED",
	3: "LOAN_STATUS_DISBURSED",
	4: "LOAN_STATUS_REPAID",
	5: "LOAN_STATUS_REJECTED",
	6: "LOAN_STATUS_CANCELLED",
}

var LoanStatus_value = map[string]int32{
	"LOAN_STATUS_UNSPECIFIED": 0,
	"LOAN_STATUS_PENDING":     1,
	"LOAN_STATUS_APPROVED":    2,
	"LOAN_STATUS_DISBURSED":   3,
	"LOAN_STATUS_REPAID":      4,
	"LOAN_STATUS_REJECTED":    5,
	"LOAN_STATUS_CANCELLED":   6,
}

func (x LoanStatus) String() string {
	return proto.EnumName(LoanStatus_name, int32(x))
}

func (LoanStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e2460db332ce6015, []int{0}
}

// Loan merupakan representasi kontrak pinjaman
type Loan struct {
	// ID unik pinjaman
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// sdk.AccAddress (dalam format bech32)
	Borrower string `protobuf:"bytes,2,opt,name=borrower,proto3" json:"borrower,omitempty"`
	// group policy address yang approve
	// audit siapa policy yang approve
	LazPolicy string `protobuf:"bytes,3,opt,name=laz_policy,json=lazPolicy,proto3" json:"laz_policy,omitempty"`
	// Nilai pokok awal peminjaman saat disetujui
	Principal *types.Coin `protobuf:"bytes,4,opt,name=principal,proto3" json:"principal,omitempty"`
	// Sisa kewajiban yang masih harus dibayar
	Outstanding *types.Coin `protobuf:"bytes,5,opt,name=outstanding,proto3" json:"outstanding,omitempty"`
	// Durasi pinjaman dalam bulan
	TenorMonths uint64 `protobuf:"varint,6,opt,name=tenor_months,json=tenorMonths,proto3" json:"tenor_months,omitempty"`
	// status pembayaran
	Status LoanStatus `protobuf:"varint,7,opt,name=status,proto3,enum=cosmos.loan.v1.LoanStatus" json:"status,omitempty"`
	// waktu saat permohonan pinjaman dibuat (block time).
	CreatedAt *time.Time `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at,omitempty"`
	// waktu saat pinjaman disetujui.
	ApprovedAt *time.Time `protobuf:"bytes,9,opt,name=approved_at,json=approvedAt,proto3,stdtime" json:"approved_at,omitempty"`
	// waktu saat dana dicairkan ke borrower.
	DisbursedAt *time.Time `protobuf:"bytes,10,opt,name=disbursed_at,json=disbursedAt,proto3,stdtime" json:"disbursed_at,omitempty"`
	// document hash (bisa pakai hash dari IPFS kalau digunakan)
	MetadataHash string `protobuf:"bytes,11,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
}

func (m *Loan) Reset()         { *m = Loan{} }
func (m *Loan) String() string { return proto.CompactTextString(m) }
func (*Loan) ProtoMessage()    {}
func (*Loan) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2460db332ce6015, []int{0}
}
func (m *Loan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Loan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Loan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Loan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loan.Merge(m, src)
}
func (m *Loan) XXX_Size() int {
	return m.Size()
}
func (m *Loan) XXX_DiscardUnknown() {
	xxx_messageInfo_Loan.DiscardUnknown(m)
}

var xxx_messageInfo_Loan proto.InternalMessageInfo

func (m *Loan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Loan) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *Loan) GetLazPolicy() string {
	if m != nil {
		return m.LazPolicy
	}
	return ""
}

func (m *Loan) GetPrincipal() *types.Coin {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *Loan) GetOutstanding() *types.Coin {
	if m != nil {
		return m.Outstanding
	}
	return nil
}

func (m *Loan) GetTenorMonths() uint64 {
	if m != nil {
		return m.TenorMonths
	}
	return 0
}

func (m *Loan) GetStatus() LoanStatus {
	if m != nil {
		return m.Status
	}
	return LoanStatus_LOAN_STATUS_UNSPECIFIED
}

func (m *Loan) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Loan) GetApprovedAt() *time.Time {
	if m != nil {
		return m.ApprovedAt
	}
	return nil
}

func (m *Loan) GetDisbursedAt() *time.Time {
	if m != nil {
		return m.DisbursedAt
	}
	return nil
}

func (m *Loan) GetMetadataHash() string {
	if m != nil {
		return m.MetadataHash
	}
	return ""
}

func init() {
	proto.RegisterEnum("cosmos.loan.v1.LoanStatus", LoanStatus_name, LoanStatus_value)
	proto.RegisterType((*Loan)(nil), "cosmos.loan.v1.Loan")
}

func init() { proto.RegisterFile("cosmos/loan/v1/loan.proto", fileDescriptor_e2460db332ce6015) }

var fileDescriptor_e2460db332ce6015 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x3d, 0x6f, 0xd3, 0x4c,
	0x1c, 0x8f, 0x53, 0x37, 0x4f, 0xf3, 0x77, 0x9f, 0xca, 0x3a, 0x0a, 0x75, 0x83, 0x70, 0x03, 0x2c,
	0x01, 0x09, 0x5b, 0x29, 0x03, 0x03, 0x03, 0x72, 0x6d, 0x03, 0x41, 0x21, 0xb5, 0xec, 0x94, 0x81,
	0xc5, 0x3a, 0xbf, 0xe0, 0x58, 0xd8, 0x3e, 0xcb, 0x77, 0x09, 0xb4, 0x9f, 0x81, 0xa1, 0x1f, 0x8a,
	0x81, 0xb1, 0x23, 0x1b, 0xa8, 0xfd, 0x22, 0xa8, 0x67, 0xa7, 0x0d, 0x5d, 0xe8, 0x74, 0x77, 0xbf,
	0x37, 0xfd, 0xef, 0x77, 0x3a, 0xd8, 0x0d, 0x09, 0xcd, 0x09, 0xd5, 0x33, 0x82, 0x0b, 0x7d, 0x31,
	0xe4, 0xab, 0x56, 0x56, 0x84, 0x11, 0xb4, 0x55, 0x53, 0x1a, 0x87, 0x16, 0xc3, 0x9e, 0xda, 0x48,
	0x03, 0x4c, 0x63, 0x7d, 0x31, 0x0c, 0x62, 0x86, 0x87, 0x7a, 0x48, 0xd2, 0x46, 0xdf, 0xdb, 0x4b,
	0x08, 0x49, 0xb2, 0x58, 0xe7, 0xa7, 0x60, 0xfe, 0x49, 0x67, 0x69, 0x1e, 0x53, 0x86, 0xf3, 0xb2,
	0x11, 0x6c, 0x27, 0x24, 0x21, 0x7c, 0xab, 0x5f, 0xee, 0x6a, 0xf4, 0xd1, 0x37, 0x11, 0xc4, 0x31,
	0xc1, 0x05, 0xda, 0x82, 0x76, 0x1a, 0x29, 0x42, 0x5f, 0x18, 0x88, 0x6e, 0x3b, 0x8d, 0x50, 0x0f,
	0x36, 0x02, 0x52, 0x55, 0xe4, 0x4b, 0x5c, 0x29, 0xed, 0xbe, 0x30, 0xe8, 0xba, 0x57, 0x67, 0xf4,
	0x00, 0x20, 0xc3, 0x27, 0x7e, 0x49, 0xb2, 0x34, 0x3c, 0x56, 0xd6, 0x38, 0xdb, 0xcd, 0xf0, 0x89,
	0xc3, 0x01, 0xf4, 0x02, 0xba, 0x65, 0x95, 0x16, 0x61, 0x5a, 0xe2, 0x4c, 0x11, 0xfb, 0xc2, 0x40,
	0xda, 0xdf, 0xd5, 0x9a, 0xeb, 0x5c, 0x8e, 0xaf, 0x35, 0xe3, 0x6b, 0x26, 0x49, 0x0b, 0xf7, 0x5a,
	0x8b, 0x5e, 0x82, 0x44, 0xe6, 0x8c, 0x32, 0x5c, 0x44, 0x69, 0x91, 0x28, 0xeb, 0xff, 0xb2, 0xae,
	0xaa, 0xd1, 0x43, 0xd8, 0x64, 0x71, 0x41, 0x2a, 0x3f, 0x27, 0x05, 0x9b, 0x51, 0xa5, 0xc3, 0xaf,
	0x22, 0x71, 0xec, 0x3d, 0x87, 0xd0, 0x3e, 0x74, 0x28, 0xc3, 0x6c, 0x4e, 0x95, 0xff, 0xfa, 0xc2,
	0x60, 0x6b, 0xbf, 0xa7, 0xfd, 0x5d, 0xb2, 0x76, 0xd9, 0x84, 0xc7, 0x15, 0x6e, 0xa3, 0x44, 0xaf,
	0x00, 0xc2, 0x2a, 0xc6, 0x2c, 0x8e, 0x7c, 0xcc, 0x94, 0x0d, 0x3e, 0x52, 0x4f, 0xab, 0xcb, 0xd6,
	0x96, 0x65, 0x6b, 0xd3, 0x65, 0xd9, 0x07, 0xe2, 0xe9, 0xaf, 0x3d, 0xc1, 0xed, 0x36, 0x1e, 0x83,
	0x21, 0x03, 0x24, 0x5c, 0x96, 0x15, 0x59, 0xd4, 0x09, 0xdd, 0x5b, 0x26, 0xc0, 0xd2, 0x64, 0x30,
	0x64, 0xc2, 0x66, 0x94, 0xd2, 0x60, 0x5e, 0xd1, 0x3a, 0x03, 0x6e, 0x99, 0x21, 0x5d, 0xb9, 0x0c,
	0x86, 0x1e, 0xc3, 0xff, 0x79, 0xcc, 0x70, 0x84, 0x19, 0xf6, 0x67, 0x98, 0xce, 0x14, 0x89, 0xbf,
	0xdb, 0xe6, 0x12, 0x7c, 0x8b, 0xe9, 0xec, 0xe9, 0x77, 0x01, 0xe0, 0xba, 0x04, 0x74, 0x1f, 0x76,
	0xc6, 0x87, 0xc6, 0xc4, 0xf7, 0xa6, 0xc6, 0xf4, 0xc8, 0xf3, 0x8f, 0x26, 0x9e, 0x63, 0x9b, 0xa3,
	0xd7, 0x23, 0xdb, 0x92, 0x5b, 0x68, 0x07, 0xee, 0xac, 0x92, 0x8e, 0x3d, 0xb1, 0x46, 0x93, 0x37,
	0xb2, 0x80, 0x14, 0xd8, 0x5e, 0x25, 0x0c, 0xc7, 0x71, 0x0f, 0x3f, 0xd8, 0x96, 0xdc, 0x46, 0xbb,
	0x70, 0x77, 0x95, 0xb1, 0x46, 0xde, 0xc1, 0x91, 0xeb, 0xd9, 0x96, 0xbc, 0x86, 0xee, 0x01, 0x5a,
	0xa5, 0x5c, 0xdb, 0x31, 0x46, 0x96, 0x2c, 0xde, 0x0c, 0x73, 0xed, 0x77, 0xb6, 0x39, 0xb5, 0x2d,
	0x79, 0xfd, 0x66, 0x98, 0x69, 0x4c, 0x4c, 0x7b, 0x3c, 0xb6, 0x2d, 0xb9, 0x73, 0x60, 0xfe, 0x38,
	0x57, 0x85, 0xb3, 0x73, 0x55, 0xf8, 0x7d, 0xae, 0x0a, 0xa7, 0x17, 0x6a, 0xeb, 0xec, 0x42, 0x6d,
	0xfd, 0xbc, 0x50, 0x5b, 0x1f, 0x9f, 0x24, 0x29, 0x9b, 0xcd, 0x03, 0x2d, 0x24, 0xb9, 0xde, 0xfc,
	0xa8, 0x7a, 0x79, 0x46, 0xa3, 0xcf, 0xfa, 0xd7, 0xfa, 0x27, 0xb2, 0xe3, 0x32, 0xa6, 0x41, 0x87,
	0xf7, 0xfa, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xa5, 0x57, 0x2e, 0xa5, 0x03, 0x00,
	0x00,
}

func (m *Loan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Loan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Loan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataHash) > 0 {
		i -= len(m.MetadataHash)
		copy(dAtA[i:], m.MetadataHash)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.MetadataHash)))
		i--
		dAtA[i] = 0x5a
	}
	if m.DisbursedAt != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.DisbursedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.DisbursedAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintLoan(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x52
	}
	if m.ApprovedAt != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ApprovedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ApprovedAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintLoan(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x4a
	}
	if m.CreatedAt != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.CreatedAt):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintLoan(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x42
	}
	if m.Status != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.TenorMonths != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.TenorMonths))
		i--
		dAtA[i] = 0x30
	}
	if m.Outstanding != nil {
		{
			size, err := m.Outstanding.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLoan(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Principal != nil {
		{
			size, err := m.Principal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLoan(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.LazPolicy) > 0 {
		i -= len(m.LazPolicy)
		copy(dAtA[i:], m.LazPolicy)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.LazPolicy)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLoan(dAtA []byte, offset int, v uint64) int {
	offset -= sovLoan(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Loan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLoan(uint64(m.Id))
	}
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.LazPolicy)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	if m.Principal != nil {
		l = m.Principal.Size()
		n += 1 + l + sovLoan(uint64(l))
	}
	if m.Outstanding != nil {
		l = m.Outstanding.Size()
		n += 1 + l + sovLoan(uint64(l))
	}
	if m.TenorMonths != 0 {
		n += 1 + sovLoan(uint64(m.TenorMonths))
	}
	if m.Status != 0 {
		n += 1 + sovLoan(uint64(m.Status))
	}
	if m.CreatedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.CreatedAt)
		n += 1 + l + sovLoan(uint64(l))
	}
	if m.ApprovedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ApprovedAt)
		n += 1 + l + sovLoan(uint64(l))
	}
	if m.DisbursedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.DisbursedAt)
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.MetadataHash)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	return n
}

func sovLoan(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLoan(x uint64) (n int) {
	return sovLoan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Loan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLoan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Loan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Loan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LazPolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LazPolicy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Principal == nil {
				m.Principal = &types.Coin{}
			}
			if err := m.Principal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outstanding", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Outstanding == nil {
				m.Outstanding = &types.Coin{}
			}
			if err := m.Outstanding.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenorMonths", wireType)
			}
			m.TenorMonths = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenorMonths |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= LoanStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ApprovedAt == nil {
				m.ApprovedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ApprovedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisbursedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DisbursedAt == nil {
				m.DisbursedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.DisbursedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLoan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLoan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLoan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLoan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLoan
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLoan
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLoan
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLoan        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLoan          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLoan = fmt.Errorf("proto: unexpected end of group")
)
