// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/loan/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams digunakan untuk mengubah parameter modul
type MsgUpdateParams struct {
	// alamat otoritas (misal governance module)
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// konfigurasi baru yang akan menggantikan params lama
	Params *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

// Response kosong karena hanya update state
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgCreateLoan digunakan oleh borrower untuk mengajukan permohonan pinjaman baru
type MsgCreateLoan struct {
	// Alamat borrower (Bech32) sebagai pemohon pinjaman
	Borrower string `protobuf:"bytes,1,opt,name=borrower,proto3" json:"borrower,omitempty"`
	// Alamat laz (Bech32) sebagai penerima pemohonan pinjaman
	Laz string `protobuf:"bytes,2,opt,name=laz,proto3" json:"laz,omitempty"`
	// Nilai pokok pinjaman yang diajukan
	Principal *types.Coin `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	// Durasi pinjaman dalam satuan bulan
	TenorMonths uint64 `protobuf:"varint,4,opt,name=tenor_months,json=tenorMonths,proto3" json:"tenor_months,omitempty"`
	// Hash dokumen pendukung (misalnya IPFS CID atau SHA256 kontrak)
	MetadataHash string `protobuf:"bytes,5,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
}

func (m *MsgCreateLoan) Reset()         { *m = MsgCreateLoan{} }
func (m *MsgCreateLoan) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLoan) ProtoMessage()    {}
func (*MsgCreateLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{2}
}
func (m *MsgCreateLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLoan.Merge(m, src)
}
func (m *MsgCreateLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLoan proto.InternalMessageInfo

func (m *MsgCreateLoan) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *MsgCreateLoan) GetLaz() string {
	if m != nil {
		return m.Laz
	}
	return ""
}

func (m *MsgCreateLoan) GetPrincipal() *types.Coin {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *MsgCreateLoan) GetTenorMonths() uint64 {
	if m != nil {
		return m.TenorMonths
	}
	return 0
}

func (m *MsgCreateLoan) GetMetadataHash() string {
	if m != nil {
		return m.MetadataHash
	}
	return ""
}

// MsgCreateLoanResponse mengembalikan ID pinjaman yang baru dibuat
type MsgCreateLoanResponse struct {
	// ID unik pinjaman yang tersimpan di state
	LoanId uint64 `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
}

func (m *MsgCreateLoanResponse) Reset()         { *m = MsgCreateLoanResponse{} }
func (m *MsgCreateLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLoanResponse) ProtoMessage()    {}
func (*MsgCreateLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{3}
}
func (m *MsgCreateLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLoanResponse.Merge(m, src)
}
func (m *MsgCreateLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLoanResponse proto.InternalMessageInfo

func (m *MsgCreateLoanResponse) GetLoanId() uint64 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

// MsgApproveLoan digunakan oleh laz yang berwenang untuk menyetujui pinjaman
type MsgApproveLoan struct {
	// Alamat (laz) sebagai otoritas persetujuan
	Laz string `protobuf:"bytes,1,opt,name=laz,proto3" json:"laz,omitempty"`
	// ID pinjaman yang akan disetujui
	LoanId uint64 `protobuf:"varint,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
}

func (m *MsgApproveLoan) Reset()         { *m = MsgApproveLoan{} }
func (m *MsgApproveLoan) String() string { return proto.CompactTextString(m) }
func (*MsgApproveLoan) ProtoMessage()    {}
func (*MsgApproveLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{4}
}
func (m *MsgApproveLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveLoan.Merge(m, src)
}
func (m *MsgApproveLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveLoan proto.InternalMessageInfo

func (m *MsgApproveLoan) GetLaz() string {
	if m != nil {
		return m.Laz
	}
	return ""
}

func (m *MsgApproveLoan) GetLoanId() uint64 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

// MsgApproveLoanResponse tidak mengembalikan data tambahan
type MsgApproveLoanResponse struct {
}

func (m *MsgApproveLoanResponse) Reset()         { *m = MsgApproveLoanResponse{} }
func (m *MsgApproveLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgApproveLoanResponse) ProtoMessage()    {}
func (*MsgApproveLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{5}
}
func (m *MsgApproveLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveLoanResponse.Merge(m, src)
}
func (m *MsgApproveLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveLoanResponse proto.InternalMessageInfo

// MsgRejectLoan digunakan oleh laz yang berwenang untuk menolak pinjaman
type MsgRejectLoan struct {
	// Alamat  sebagai otoritas penolakan
	Laz string `protobuf:"bytes,1,opt,name=laz,proto3" json:"laz,omitempty"`
	// ID pinjaman yang akan ditolak
	LoanId uint64 `protobuf:"varint,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
}

func (m *MsgRejectLoan) Reset()         { *m = MsgRejectLoan{} }
func (m *MsgRejectLoan) String() string { return proto.CompactTextString(m) }
func (*MsgRejectLoan) ProtoMessage()    {}
func (*MsgRejectLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{6}
}
func (m *MsgRejectLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectLoan.Merge(m, src)
}
func (m *MsgRejectLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectLoan proto.InternalMessageInfo

func (m *MsgRejectLoan) GetLaz() string {
	if m != nil {
		return m.Laz
	}
	return ""
}

func (m *MsgRejectLoan) GetLoanId() uint64 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

// MsgRejectLoanResponse tidak mengembalikan data tambahan
type MsgRejectLoanResponse struct {
}

func (m *MsgRejectLoanResponse) Reset()         { *m = MsgRejectLoanResponse{} }
func (m *MsgRejectLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRejectLoanResponse) ProtoMessage()    {}
func (*MsgRejectLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{7}
}
func (m *MsgRejectLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectLoanResponse.Merge(m, src)
}
func (m *MsgRejectLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectLoanResponse proto.InternalMessageInfo

// MsgRepayLoan digunakan untuk mencatat pembayaran pinjaman yang dihasilkan oleh omnibus
type MsgRepayLoan struct {
	// Alamat omnibus sebagai otoritas pembayaran
	Omnibus string `protobuf:"bytes,1,opt,name=omnibus,proto3" json:"omnibus,omitempty"`
	// ID pinjaman yang dibayar
	LoanId uint64 `protobuf:"varint,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	// Jumlah yang dibayarkan
	Amount *types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgRepayLoan) Reset()         { *m = MsgRepayLoan{} }
func (m *MsgRepayLoan) String() string { return proto.CompactTextString(m) }
func (*MsgRepayLoan) ProtoMessage()    {}
func (*MsgRepayLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{8}
}
func (m *MsgRepayLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRepayLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRepayLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRepayLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRepayLoan.Merge(m, src)
}
func (m *MsgRepayLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgRepayLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRepayLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRepayLoan proto.InternalMessageInfo

func (m *MsgRepayLoan) GetOmnibus() string {
	if m != nil {
		return m.Omnibus
	}
	return ""
}

func (m *MsgRepayLoan) GetLoanId() uint64 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

func (m *MsgRepayLoan) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

// MsgRepayLoanResponse tidak mengembalikan data tambahan
type MsgRepayLoanResponse struct {
}

func (m *MsgRepayLoanResponse) Reset()         { *m = MsgRepayLoanResponse{} }
func (m *MsgRepayLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRepayLoanResponse) ProtoMessage()    {}
func (*MsgRepayLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{9}
}
func (m *MsgRepayLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRepayLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRepayLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRepayLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRepayLoanResponse.Merge(m, src)
}
func (m *MsgRepayLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRepayLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRepayLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRepayLoanResponse proto.InternalMessageInfo

// MsgConfirmDisbursement digunakan untuk mengonfirmasi bahwa dana telah dicairkan
type MsgConfirmDisbursement struct {
	// Alamat omnibus sebagai otoritas pencairan dana
	Omnibus string `protobuf:"bytes,1,opt,name=omnibus,proto3" json:"omnibus,omitempty"`
	// ID pinjaman yang dicairkan
	LoanId uint64 `protobuf:"varint,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
}

func (m *MsgConfirmDisbursement) Reset()         { *m = MsgConfirmDisbursement{} }
func (m *MsgConfirmDisbursement) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmDisbursement) ProtoMessage()    {}
func (*MsgConfirmDisbursement) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{10}
}
func (m *MsgConfirmDisbursement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmDisbursement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmDisbursement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmDisbursement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmDisbursement.Merge(m, src)
}
func (m *MsgConfirmDisbursement) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmDisbursement) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmDisbursement.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmDisbursement proto.InternalMessageInfo

func (m *MsgConfirmDisbursement) GetOmnibus() string {
	if m != nil {
		return m.Omnibus
	}
	return ""
}

func (m *MsgConfirmDisbursement) GetLoanId() uint64 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

// MsgConfirmDisbursementResponse tidak mengembalikan data tambahan
type MsgConfirmDisbursementResponse struct {
}

func (m *MsgConfirmDisbursementResponse) Reset()         { *m = MsgConfirmDisbursementResponse{} }
func (m *MsgConfirmDisbursementResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmDisbursementResponse) ProtoMessage()    {}
func (*MsgConfirmDisbursementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{11}
}
func (m *MsgConfirmDisbursementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmDisbursementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmDisbursementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmDisbursementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmDisbursementResponse.Merge(m, src)
}
func (m *MsgConfirmDisbursementResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmDisbursementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmDisbursementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmDisbursementResponse proto.InternalMessageInfo

// MsgRejectDisbursement, Omnibus dalam kasus tertentu, menolak pencairan dana pinjaman yang sudah disetujui
// cth: layanan error, bank transfer gagal, rekening borrower invalid, etc
type MsgRejectDisbursement struct {
	// alamat omnibus yang berwenang menolak pencairan
	Omnibus string `protobuf:"bytes,1,opt,name=omnibus,proto3" json:"omnibus,omitempty"`
	// ID pinjaman yang pencairannya ditolak
	LoanId uint64 `protobuf:"varint,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	// alasan penolakan pencairan
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgRejectDisbursement) Reset()         { *m = MsgRejectDisbursement{} }
func (m *MsgRejectDisbursement) String() string { return proto.CompactTextString(m) }
func (*MsgRejectDisbursement) ProtoMessage()    {}
func (*MsgRejectDisbursement) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{12}
}
func (m *MsgRejectDisbursement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectDisbursement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectDisbursement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectDisbursement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectDisbursement.Merge(m, src)
}
func (m *MsgRejectDisbursement) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectDisbursement) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectDisbursement.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectDisbursement proto.InternalMessageInfo

func (m *MsgRejectDisbursement) GetOmnibus() string {
	if m != nil {
		return m.Omnibus
	}
	return ""
}

func (m *MsgRejectDisbursement) GetLoanId() uint64 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

func (m *MsgRejectDisbursement) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// MsgRejectDisbursementResponse tidak mengembalikan data tambahan
type MsgRejectDisbursementResponse struct {
}

func (m *MsgRejectDisbursementResponse) Reset()         { *m = MsgRejectDisbursementResponse{} }
func (m *MsgRejectDisbursementResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRejectDisbursementResponse) ProtoMessage()    {}
func (*MsgRejectDisbursementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73b61ff6b54bde18, []int{13}
}
func (m *MsgRejectDisbursementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRejectDisbursementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRejectDisbursementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRejectDisbursementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRejectDisbursementResponse.Merge(m, src)
}
func (m *MsgRejectDisbursementResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRejectDisbursementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRejectDisbursementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRejectDisbursementResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "cosmos.loan.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "cosmos.loan.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateLoan)(nil), "cosmos.loan.v1.MsgCreateLoan")
	proto.RegisterType((*MsgCreateLoanResponse)(nil), "cosmos.loan.v1.MsgCreateLoanResponse")
	proto.RegisterType((*MsgApproveLoan)(nil), "cosmos.loan.v1.MsgApproveLoan")
	proto.RegisterType((*MsgApproveLoanResponse)(nil), "cosmos.loan.v1.MsgApproveLoanResponse")
	proto.RegisterType((*MsgRejectLoan)(nil), "cosmos.loan.v1.MsgRejectLoan")
	proto.RegisterType((*MsgRejectLoanResponse)(nil), "cosmos.loan.v1.MsgRejectLoanResponse")
	proto.RegisterType((*MsgRepayLoan)(nil), "cosmos.loan.v1.MsgRepayLoan")
	proto.RegisterType((*MsgRepayLoanResponse)(nil), "cosmos.loan.v1.MsgRepayLoanResponse")
	proto.RegisterType((*MsgConfirmDisbursement)(nil), "cosmos.loan.v1.MsgConfirmDisbursement")
	proto.RegisterType((*MsgConfirmDisbursementResponse)(nil), "cosmos.loan.v1.MsgConfirmDisbursementResponse")
	proto.RegisterType((*MsgRejectDisbursement)(nil), "cosmos.loan.v1.MsgRejectDisbursement")
	proto.RegisterType((*MsgRejectDisbursementResponse)(nil), "cosmos.loan.v1.MsgRejectDisbursementResponse")
}

func init() { proto.RegisterFile("cosmos/loan/v1/tx.proto", fileDescriptor_73b61ff6b54bde18) }

var fileDescriptor_73b61ff6b54bde18 = []byte{
	// 735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcb, 0x6e, 0xd3, 0x4c,
	0x18, 0xad, 0x7b, 0x49, 0x9b, 0xaf, 0x69, 0x7f, 0xc9, 0x7f, 0x49, 0x52, 0x43, 0xdd, 0x10, 0x6e,
	0xa5, 0x52, 0x1d, 0x52, 0x10, 0x48, 0xd9, 0xb5, 0x61, 0x01, 0x12, 0x11, 0xc8, 0xa8, 0x12, 0x62,
	0x41, 0x34, 0x49, 0x06, 0xc7, 0xa5, 0x9e, 0xb1, 0x66, 0x26, 0xa1, 0x65, 0x05, 0xec, 0x60, 0x05,
	0x7b, 0x1e, 0xa2, 0x0b, 0x1e, 0x82, 0x65, 0xc5, 0x8a, 0x25, 0x6a, 0x17, 0x7d, 0x0d, 0xe4, 0xf1,
	0x35, 0xc1, 0x4d, 0xba, 0xa0, 0x2b, 0xcb, 0x73, 0xce, 0x9c, 0xef, 0x7c, 0x67, 0x6e, 0x50, 0x68,
	0x53, 0xee, 0x50, 0x5e, 0xd9, 0xa3, 0x88, 0x54, 0xfa, 0xd5, 0x8a, 0xd8, 0x37, 0x5c, 0x46, 0x05,
	0x55, 0x17, 0x7d, 0xc0, 0xf0, 0x00, 0xa3, 0x5f, 0xd5, 0xf4, 0x80, 0xd8, 0x42, 0x1c, 0x57, 0xfa,
	0xd5, 0x16, 0x16, 0xa8, 0x5a, 0x69, 0x53, 0x9b, 0xf8, 0x7c, 0x2d, 0x14, 0x72, 0xb8, 0xe5, 0xe9,
	0x38, 0xdc, 0x0a, 0x80, 0x65, 0x1f, 0x68, 0xca, 0xbf, 0x4a, 0xa0, 0xea, 0x43, 0x97, 0x87, 0x8a,
	0xbb, 0x88, 0x21, 0x27, 0x00, 0xcb, 0x9f, 0x14, 0xf8, 0xaf, 0xc1, 0xad, 0x1d, 0xb7, 0x83, 0x04,
	0x7e, 0x26, 0x11, 0xf5, 0x3e, 0x64, 0x51, 0x4f, 0x74, 0x29, 0xb3, 0xc5, 0x41, 0x51, 0x29, 0x29,
	0x6b, 0xd9, 0xed, 0xe2, 0xcf, 0xef, 0x1b, 0x4b, 0x81, 0xea, 0x56, 0xa7, 0xc3, 0x30, 0xe7, 0xcf,
	0x05, 0xb3, 0x89, 0x65, 0xc6, 0x54, 0xd5, 0x80, 0x8c, 0xaf, 0x5d, 0x9c, 0x2c, 0x29, 0x6b, 0xf3,
	0x9b, 0x79, 0x63, 0xb0, 0x3b, 0xc3, 0xd7, 0x37, 0x03, 0x56, 0x6d, 0xf1, 0xe3, 0xe9, 0xe1, 0x7a,
	0x3c, 0xbf, 0xbc, 0x0c, 0x85, 0x21, 0x2b, 0x26, 0xe6, 0x2e, 0x25, 0x1c, 0x97, 0x3f, 0x4c, 0xc2,
	0x42, 0x83, 0x5b, 0x75, 0x86, 0x91, 0xc0, 0x4f, 0x28, 0x22, 0xea, 0x3d, 0x98, 0x6b, 0x51, 0xc6,
	0xe8, 0x5b, 0xcc, 0xc6, 0x7a, 0x8c, 0x98, 0xea, 0x3a, 0x4c, 0xed, 0xa1, 0x77, 0xd2, 0xdf, 0xa8,
	0x09, 0x1e, 0x49, 0x7d, 0x00, 0x59, 0x97, 0xd9, 0xa4, 0x6d, 0xbb, 0x68, 0xaf, 0x38, 0x25, 0x3b,
	0x5a, 0x0e, 0x3b, 0xf2, 0xd6, 0xc7, 0x08, 0xd6, 0xc7, 0xa8, 0x53, 0x9b, 0x98, 0x31, 0x57, 0xbd,
	0x0a, 0x39, 0x81, 0x09, 0x65, 0x4d, 0x87, 0x12, 0xd1, 0xe5, 0xc5, 0xe9, 0x92, 0xb2, 0x36, 0x6d,
	0xce, 0xcb, 0xb1, 0x86, 0x1c, 0x52, 0xaf, 0xc1, 0x82, 0x83, 0x05, 0xea, 0x20, 0x81, 0x9a, 0x5d,
	0xc4, 0xbb, 0xc5, 0x19, 0xcf, 0x91, 0x99, 0x0b, 0x07, 0x1f, 0x21, 0xde, 0xad, 0x2d, 0x78, 0xf9,
	0x44, 0xde, 0xcb, 0x77, 0xe0, 0xd2, 0x40, 0x04, 0x61, 0x38, 0x6a, 0x01, 0x66, 0xbd, 0x84, 0x9b,
	0x76, 0x47, 0x26, 0x31, 0x6d, 0x66, 0xbc, 0xdf, 0xc7, 0x9d, 0x72, 0x13, 0x16, 0x1b, 0xdc, 0xda,
	0x72, 0x5d, 0x46, 0xfb, 0x7e, 0x6a, 0x41, 0xff, 0xca, 0x79, 0xfa, 0x4f, 0xc8, 0x4e, 0x26, 0x65,
	0x6b, 0x73, 0x9e, 0x2f, 0x8f, 0x52, 0x2e, 0x42, 0x7e, 0xb0, 0x40, 0xb4, 0x60, 0xaf, 0xe4, 0x7a,
	0x99, 0x78, 0x17, 0xb7, 0xc5, 0x45, 0x54, 0x2e, 0xc8, 0x30, 0x62, 0xfd, 0xa8, 0xf0, 0x37, 0x05,
	0x72, 0x12, 0x71, 0xd1, 0x81, 0x2c, 0xbc, 0x09, 0xb3, 0xd4, 0x21, 0x76, 0xab, 0xc7, 0xc7, 0x16,
	0x0f, 0x89, 0x67, 0x1a, 0x50, 0xab, 0x90, 0x41, 0x0e, 0xed, 0x11, 0x31, 0x7e, 0x43, 0x04, 0xc4,
	0x5a, 0xce, 0xf3, 0x1c, 0x2a, 0x97, 0xf3, 0xb0, 0x94, 0x74, 0x17, 0xd9, 0xe6, 0x32, 0xc9, 0x3a,
	0x25, 0xaf, 0x6d, 0xe6, 0x3c, 0xb4, 0x79, 0xab, 0xc7, 0x38, 0x76, 0x30, 0x11, 0xff, 0xd4, 0xff,
	0x90, 0x99, 0x12, 0xe8, 0xe9, 0x45, 0x23, 0x5b, 0x9f, 0x95, 0x44, 0xce, 0x17, 0x66, 0x4b, 0xcd,
	0x43, 0x86, 0x61, 0xc4, 0x29, 0x91, 0xb1, 0x66, 0xcd, 0xe0, 0x6f, 0xc8, 0xee, 0x2a, 0xac, 0xa4,
	0x7a, 0x09, 0xdd, 0x6e, 0x7e, 0x9d, 0x81, 0xa9, 0x06, 0xb7, 0xd4, 0x17, 0x90, 0x1b, 0xb8, 0xd0,
	0x56, 0x87, 0x2f, 0xa2, 0xa1, 0x6b, 0x46, 0xbb, 0x35, 0x86, 0x10, 0x1d, 0x35, 0x13, 0x20, 0x71,
	0x07, 0xad, 0xa4, 0x4c, 0x8b, 0x61, 0xed, 0xc6, 0x48, 0x38, 0xd2, 0xdc, 0x81, 0xf9, 0xe4, 0x11,
	0xd5, 0x53, 0x66, 0x25, 0x70, 0xed, 0xe6, 0x68, 0x3c, 0x69, 0x35, 0x71, 0xfc, 0xd2, 0xac, 0xc6,
	0x70, 0xaa, 0xd5, 0xbf, 0x0f, 0x97, 0xfa, 0x14, 0xb2, 0xf1, 0xc1, 0xba, 0x92, 0x3a, 0x27, 0x40,
	0xb5, 0xeb, 0xa3, 0xd0, 0x48, 0xd0, 0x81, 0xff, 0xd3, 0xf6, 0x7c, 0x5a, 0x8f, 0x29, 0x3c, 0xcd,
	0x38, 0x1f, 0x2f, 0x2a, 0xb7, 0x0b, 0x6a, 0xca, 0x56, 0x3e, 0xbb, 0xf9, 0x81, 0x62, 0x1b, 0xe7,
	0xa2, 0x85, 0xb5, 0xb4, 0x99, 0xf7, 0xa7, 0x87, 0xeb, 0xca, 0x76, 0xfd, 0xc7, 0xb1, 0xae, 0x1c,
	0x1d, 0xeb, 0xca, 0xef, 0x63, 0x5d, 0xf9, 0x72, 0xa2, 0x4f, 0x1c, 0x9d, 0xe8, 0x13, 0xbf, 0x4e,
	0xf4, 0x89, 0x97, 0xb7, 0x2d, 0x5b, 0x74, 0x7b, 0x2d, 0xa3, 0x4d, 0x9d, 0xe0, 0xc1, 0x0e, 0x3e,
	0x1b, 0xbc, 0xf3, 0xa6, 0xb2, 0xef, 0xbf, 0xd7, 0xe2, 0xc0, 0xc5, 0xbc, 0x95, 0x91, 0x8f, 0xf5,
	0xdd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xc6, 0x75, 0x1a, 0x48, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Mengubah konfigurasi global modul (hanya authority)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// Membuat permohonan pinjaman baru dengan status PENDING oleh borrower
	CreateLoan(ctx context.Context, in *MsgCreateLoan, opts ...grpc.CallOption) (*MsgCreateLoanResponse, error)
	// Menyetujui pinjaman berstatus PENDING oleh laz yang berwenang
	// status berubah jadi APPROVED
	ApproveLoan(ctx context.Context, in *MsgApproveLoan, opts ...grpc.CallOption) (*MsgApproveLoanResponse, error)
	// Menolak pinjaman berstatus PENDING oleh laz yang berwenang
	// status berubah jadi REJECTED
	RejectLoan(ctx context.Context, in *MsgRejectLoan, opts ...grpc.CallOption) (*MsgRejectLoanResponse, error)
	// Mencatat pembayaran pinjaman oleh omnibus
	// Mengurangi outstanding dan membakar settlement token
	RepayLoan(ctx context.Context, in *MsgRepayLoan, opts ...grpc.CallOption) (*MsgRepayLoanResponse, error)
	// Mengonfirmasi pencairan dana dan mengubah status menjadi DISBURSED
	ConfirmDisbursement(ctx context.Context, in *MsgConfirmDisbursement, opts ...grpc.CallOption) (*MsgConfirmDisbursementResponse, error)
	// Menolak pencairan dana pinjaman yang sudah disetujui
	RejectDisbursement(ctx context.Context, in *MsgRejectDisbursement, opts ...grpc.CallOption) (*MsgRejectDisbursementResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.loan.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateLoan(ctx context.Context, in *MsgCreateLoan, opts ...grpc.CallOption) (*MsgCreateLoanResponse, error) {
	out := new(MsgCreateLoanResponse)
	err := c.cc.Invoke(ctx, "/cosmos.loan.v1.Msg/CreateLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApproveLoan(ctx context.Context, in *MsgApproveLoan, opts ...grpc.CallOption) (*MsgApproveLoanResponse, error) {
	out := new(MsgApproveLoanResponse)
	err := c.cc.Invoke(ctx, "/cosmos.loan.v1.Msg/ApproveLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectLoan(ctx context.Context, in *MsgRejectLoan, opts ...grpc.CallOption) (*MsgRejectLoanResponse, error) {
	out := new(MsgRejectLoanResponse)
	err := c.cc.Invoke(ctx, "/cosmos.loan.v1.Msg/RejectLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RepayLoan(ctx context.Context, in *MsgRepayLoan, opts ...grpc.CallOption) (*MsgRepayLoanResponse, error) {
	out := new(MsgRepayLoanResponse)
	err := c.cc.Invoke(ctx, "/cosmos.loan.v1.Msg/RepayLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfirmDisbursement(ctx context.Context, in *MsgConfirmDisbursement, opts ...grpc.CallOption) (*MsgConfirmDisbursementResponse, error) {
	out := new(MsgConfirmDisbursementResponse)
	err := c.cc.Invoke(ctx, "/cosmos.loan.v1.Msg/ConfirmDisbursement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectDisbursement(ctx context.Context, in *MsgRejectDisbursement, opts ...grpc.CallOption) (*MsgRejectDisbursementResponse, error) {
	out := new(MsgRejectDisbursementResponse)
	err := c.cc.Invoke(ctx, "/cosmos.loan.v1.Msg/RejectDisbursement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Mengubah konfigurasi global modul (hanya authority)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// Membuat permohonan pinjaman baru dengan status PENDING oleh borrower
	CreateLoan(context.Context, *MsgCreateLoan) (*MsgCreateLoanResponse, error)
	// Menyetujui pinjaman berstatus PENDING oleh laz yang berwenang
	// status berubah jadi APPROVED
	ApproveLoan(context.Context, *MsgApproveLoan) (*MsgApproveLoanResponse, error)
	// Menolak pinjaman berstatus PENDING oleh laz yang berwenang
	// status berubah jadi REJECTED
	RejectLoan(context.Context, *MsgRejectLoan) (*MsgRejectLoanResponse, error)
	// Mencatat pembayaran pinjaman oleh omnibus
	// Mengurangi outstanding dan membakar settlement token
	RepayLoan(context.Context, *MsgRepayLoan) (*MsgRepayLoanResponse, error)
	// Mengonfirmasi pencairan dana dan mengubah status menjadi DISBURSED
	ConfirmDisbursement(context.Context, *MsgConfirmDisbursement) (*MsgConfirmDisbursementResponse, error)
	// Menolak pencairan dana pinjaman yang sudah disetujui
	RejectDisbursement(context.Context, *MsgRejectDisbursement) (*MsgRejectDisbursementResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateLoan(ctx context.Context, req *MsgCreateLoan) (*MsgCreateLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoan not implemented")
}
func (*UnimplementedMsgServer) ApproveLoan(ctx context.Context, req *MsgApproveLoan) (*MsgApproveLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveLoan not implemented")
}
func (*UnimplementedMsgServer) RejectLoan(ctx context.Context, req *MsgRejectLoan) (*MsgRejectLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectLoan not implemented")
}
func (*UnimplementedMsgServer) RepayLoan(ctx context.Context, req *MsgRepayLoan) (*MsgRepayLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepayLoan not implemented")
}
func (*UnimplementedMsgServer) ConfirmDisbursement(ctx context.Context, req *MsgConfirmDisbursement) (*MsgConfirmDisbursementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmDisbursement not implemented")
}
func (*UnimplementedMsgServer) RejectDisbursement(ctx context.Context, req *MsgRejectDisbursement) (*MsgRejectDisbursementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectDisbursement not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.loan.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.loan.v1.Msg/CreateLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLoan(ctx, req.(*MsgCreateLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApproveLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.loan.v1.Msg/ApproveLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveLoan(ctx, req.(*MsgApproveLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.loan.v1.Msg/RejectLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectLoan(ctx, req.(*MsgRejectLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RepayLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRepayLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RepayLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.loan.v1.Msg/RepayLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RepayLoan(ctx, req.(*MsgRepayLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfirmDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmDisbursement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.loan.v1.Msg/ConfirmDisbursement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmDisbursement(ctx, req.(*MsgConfirmDisbursement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectDisbursement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectDisbursement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectDisbursement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.loan.v1.Msg/RejectDisbursement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectDisbursement(ctx, req.(*MsgRejectDisbursement))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.loan.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateLoan",
			Handler:    _Msg_CreateLoan_Handler,
		},
		{
			MethodName: "ApproveLoan",
			Handler:    _Msg_ApproveLoan_Handler,
		},
		{
			MethodName: "RejectLoan",
			Handler:    _Msg_RejectLoan_Handler,
		},
		{
			MethodName: "RepayLoan",
			Handler:    _Msg_RepayLoan_Handler,
		},
		{
			MethodName: "ConfirmDisbursement",
			Handler:    _Msg_ConfirmDisbursement_Handler,
		},
		{
			MethodName: "RejectDisbursement",
			Handler:    _Msg_RejectDisbursement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/loan/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataHash) > 0 {
		i -= len(m.MetadataHash)
		copy(dAtA[i:], m.MetadataHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MetadataHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.TenorMonths != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TenorMonths))
		i--
		dAtA[i] = 0x20
	}
	if m.Principal != nil {
		{
			size, err := m.Principal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Laz) > 0 {
		i -= len(m.Laz)
		copy(dAtA[i:], m.Laz)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Laz)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LoanId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LoanId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgApproveLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LoanId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LoanId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Laz) > 0 {
		i -= len(m.Laz)
		copy(dAtA[i:], m.Laz)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Laz)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgApproveLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRejectLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LoanId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LoanId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Laz) > 0 {
		i -= len(m.Laz)
		copy(dAtA[i:], m.Laz)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Laz)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRejectLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRepayLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRepayLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRepayLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.LoanId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LoanId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Omnibus) > 0 {
		i -= len(m.Omnibus)
		copy(dAtA[i:], m.Omnibus)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Omnibus)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRepayLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRepayLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRepayLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgConfirmDisbursement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmDisbursement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmDisbursement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LoanId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LoanId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Omnibus) > 0 {
		i -= len(m.Omnibus)
		copy(dAtA[i:], m.Omnibus)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Omnibus)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfirmDisbursementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmDisbursementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmDisbursementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRejectDisbursement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectDisbursement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectDisbursement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LoanId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LoanId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Omnibus) > 0 {
		i -= len(m.Omnibus)
		copy(dAtA[i:], m.Omnibus)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Omnibus)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRejectDisbursementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRejectDisbursementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRejectDisbursementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Laz)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Principal != nil {
		l = m.Principal.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TenorMonths != 0 {
		n += 1 + sovTx(uint64(m.TenorMonths))
	}
	l = len(m.MetadataHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LoanId != 0 {
		n += 1 + sovTx(uint64(m.LoanId))
	}
	return n
}

func (m *MsgApproveLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Laz)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LoanId != 0 {
		n += 1 + sovTx(uint64(m.LoanId))
	}
	return n
}

func (m *MsgApproveLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRejectLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Laz)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LoanId != 0 {
		n += 1 + sovTx(uint64(m.LoanId))
	}
	return n
}

func (m *MsgRejectLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRepayLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Omnibus)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LoanId != 0 {
		n += 1 + sovTx(uint64(m.LoanId))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRepayLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgConfirmDisbursement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Omnibus)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LoanId != 0 {
		n += 1 + sovTx(uint64(m.LoanId))
	}
	return n
}

func (m *MsgConfirmDisbursementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRejectDisbursement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Omnibus)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LoanId != 0 {
		n += 1 + sovTx(uint64(m.LoanId))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRejectDisbursementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Laz", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Laz = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Principal == nil {
				m.Principal = &types.Coin{}
			}
			if err := m.Principal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenorMonths", wireType)
			}
			m.TenorMonths = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenorMonths |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
			}
			m.LoanId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoanId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApproveLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Laz", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Laz = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
			}
			m.LoanId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoanId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApproveLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Laz", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Laz = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
			}
			m.LoanId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoanId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRepayLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRepayLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRepayLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Omnibus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Omnibus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
			}
			m.LoanId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoanId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRepayLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRepayLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRepayLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmDisbursement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmDisbursement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmDisbursement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Omnibus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Omnibus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
			}
			m.LoanId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoanId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmDisbursementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmDisbursementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmDisbursementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectDisbursement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectDisbursement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectDisbursement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Omnibus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Omnibus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
			}
			m.LoanId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoanId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRejectDisbursementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRejectDisbursementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRejectDisbursementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
