// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package loanv1

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/v1beta1"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Loan               protoreflect.MessageDescriptor
	fd_Loan_id            protoreflect.FieldDescriptor
	fd_Loan_borrower      protoreflect.FieldDescriptor
	fd_Loan_laz_policy    protoreflect.FieldDescriptor
	fd_Loan_principal     protoreflect.FieldDescriptor
	fd_Loan_outstanding   protoreflect.FieldDescriptor
	fd_Loan_tenor_months  protoreflect.FieldDescriptor
	fd_Loan_status        protoreflect.FieldDescriptor
	fd_Loan_created_at    protoreflect.FieldDescriptor
	fd_Loan_approved_at   protoreflect.FieldDescriptor
	fd_Loan_disbursed_at  protoreflect.FieldDescriptor
	fd_Loan_metadata_hash protoreflect.FieldDescriptor
)

func init() {
	file_overloan_loan_v1_loan_proto_init()
	md_Loan = File_overloan_loan_v1_loan_proto.Messages().ByName("Loan")
	fd_Loan_id = md_Loan.Fields().ByName("id")
	fd_Loan_borrower = md_Loan.Fields().ByName("borrower")
	fd_Loan_laz_policy = md_Loan.Fields().ByName("laz_policy")
	fd_Loan_principal = md_Loan.Fields().ByName("principal")
	fd_Loan_outstanding = md_Loan.Fields().ByName("outstanding")
	fd_Loan_tenor_months = md_Loan.Fields().ByName("tenor_months")
	fd_Loan_status = md_Loan.Fields().ByName("status")
	fd_Loan_created_at = md_Loan.Fields().ByName("created_at")
	fd_Loan_approved_at = md_Loan.Fields().ByName("approved_at")
	fd_Loan_disbursed_at = md_Loan.Fields().ByName("disbursed_at")
	fd_Loan_metadata_hash = md_Loan.Fields().ByName("metadata_hash")
}

var _ protoreflect.Message = (*fastReflection_Loan)(nil)

type fastReflection_Loan Loan

func (x *Loan) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Loan)(x)
}

func (x *Loan) slowProtoReflect() protoreflect.Message {
	mi := &file_overloan_loan_v1_loan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Loan_messageType fastReflection_Loan_messageType
var _ protoreflect.MessageType = fastReflection_Loan_messageType{}

type fastReflection_Loan_messageType struct{}

func (x fastReflection_Loan_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Loan)(nil)
}
func (x fastReflection_Loan_messageType) New() protoreflect.Message {
	return new(fastReflection_Loan)
}
func (x fastReflection_Loan_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Loan
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Loan) Descriptor() protoreflect.MessageDescriptor {
	return md_Loan
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Loan) Type() protoreflect.MessageType {
	return _fastReflection_Loan_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Loan) New() protoreflect.Message {
	return new(fastReflection_Loan)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Loan) Interface() protoreflect.ProtoMessage {
	return (*Loan)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Loan) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Loan_id, value) {
			return
		}
	}
	if x.Borrower != "" {
		value := protoreflect.ValueOfString(x.Borrower)
		if !f(fd_Loan_borrower, value) {
			return
		}
	}
	if x.LazPolicy != "" {
		value := protoreflect.ValueOfString(x.LazPolicy)
		if !f(fd_Loan_laz_policy, value) {
			return
		}
	}
	if x.Principal != nil {
		value := protoreflect.ValueOfMessage(x.Principal.ProtoReflect())
		if !f(fd_Loan_principal, value) {
			return
		}
	}
	if x.Outstanding != nil {
		value := protoreflect.ValueOfMessage(x.Outstanding.ProtoReflect())
		if !f(fd_Loan_outstanding, value) {
			return
		}
	}
	if x.TenorMonths != uint64(0) {
		value := protoreflect.ValueOfUint64(x.TenorMonths)
		if !f(fd_Loan_tenor_months, value) {
			return
		}
	}
	if x.Status != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Status))
		if !f(fd_Loan_status, value) {
			return
		}
	}
	if x.CreatedAt != nil {
		value := protoreflect.ValueOfMessage(x.CreatedAt.ProtoReflect())
		if !f(fd_Loan_created_at, value) {
			return
		}
	}
	if x.ApprovedAt != nil {
		value := protoreflect.ValueOfMessage(x.ApprovedAt.ProtoReflect())
		if !f(fd_Loan_approved_at, value) {
			return
		}
	}
	if x.DisbursedAt != nil {
		value := protoreflect.ValueOfMessage(x.DisbursedAt.ProtoReflect())
		if !f(fd_Loan_disbursed_at, value) {
			return
		}
	}
	if x.MetadataHash != "" {
		value := protoreflect.ValueOfString(x.MetadataHash)
		if !f(fd_Loan_metadata_hash, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Loan) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "loan.v1.Loan.id":
		return x.Id != uint64(0)
	case "loan.v1.Loan.borrower":
		return x.Borrower != ""
	case "loan.v1.Loan.laz_policy":
		return x.LazPolicy != ""
	case "loan.v1.Loan.principal":
		return x.Principal != nil
	case "loan.v1.Loan.outstanding":
		return x.Outstanding != nil
	case "loan.v1.Loan.tenor_months":
		return x.TenorMonths != uint64(0)
	case "loan.v1.Loan.status":
		return x.Status != 0
	case "loan.v1.Loan.created_at":
		return x.CreatedAt != nil
	case "loan.v1.Loan.approved_at":
		return x.ApprovedAt != nil
	case "loan.v1.Loan.disbursed_at":
		return x.DisbursedAt != nil
	case "loan.v1.Loan.metadata_hash":
		return x.MetadataHash != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: loan.v1.Loan"))
		}
		panic(fmt.Errorf("message loan.v1.Loan does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Loan) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "loan.v1.Loan.id":
		x.Id = uint64(0)
	case "loan.v1.Loan.borrower":
		x.Borrower = ""
	case "loan.v1.Loan.laz_policy":
		x.LazPolicy = ""
	case "loan.v1.Loan.principal":
		x.Principal = nil
	case "loan.v1.Loan.outstanding":
		x.Outstanding = nil
	case "loan.v1.Loan.tenor_months":
		x.TenorMonths = uint64(0)
	case "loan.v1.Loan.status":
		x.Status = 0
	case "loan.v1.Loan.created_at":
		x.CreatedAt = nil
	case "loan.v1.Loan.approved_at":
		x.ApprovedAt = nil
	case "loan.v1.Loan.disbursed_at":
		x.DisbursedAt = nil
	case "loan.v1.Loan.metadata_hash":
		x.MetadataHash = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: loan.v1.Loan"))
		}
		panic(fmt.Errorf("message loan.v1.Loan does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Loan) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "loan.v1.Loan.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "loan.v1.Loan.borrower":
		value := x.Borrower
		return protoreflect.ValueOfString(value)
	case "loan.v1.Loan.laz_policy":
		value := x.LazPolicy
		return protoreflect.ValueOfString(value)
	case "loan.v1.Loan.principal":
		value := x.Principal
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "loan.v1.Loan.outstanding":
		value := x.Outstanding
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "loan.v1.Loan.tenor_months":
		value := x.TenorMonths
		return protoreflect.ValueOfUint64(value)
	case "loan.v1.Loan.status":
		value := x.Status
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "loan.v1.Loan.created_at":
		value := x.CreatedAt
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "loan.v1.Loan.approved_at":
		value := x.ApprovedAt
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "loan.v1.Loan.disbursed_at":
		value := x.DisbursedAt
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "loan.v1.Loan.metadata_hash":
		value := x.MetadataHash
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: loan.v1.Loan"))
		}
		panic(fmt.Errorf("message loan.v1.Loan does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Loan) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "loan.v1.Loan.id":
		x.Id = value.Uint()
	case "loan.v1.Loan.borrower":
		x.Borrower = value.Interface().(string)
	case "loan.v1.Loan.laz_policy":
		x.LazPolicy = value.Interface().(string)
	case "loan.v1.Loan.principal":
		x.Principal = value.Message().Interface().(*v1beta1.Coin)
	case "loan.v1.Loan.outstanding":
		x.Outstanding = value.Message().Interface().(*v1beta1.Coin)
	case "loan.v1.Loan.tenor_months":
		x.TenorMonths = value.Uint()
	case "loan.v1.Loan.status":
		x.Status = (LoanStatus)(value.Enum())
	case "loan.v1.Loan.created_at":
		x.CreatedAt = value.Message().Interface().(*timestamppb.Timestamp)
	case "loan.v1.Loan.approved_at":
		x.ApprovedAt = value.Message().Interface().(*timestamppb.Timestamp)
	case "loan.v1.Loan.disbursed_at":
		x.DisbursedAt = value.Message().Interface().(*timestamppb.Timestamp)
	case "loan.v1.Loan.metadata_hash":
		x.MetadataHash = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: loan.v1.Loan"))
		}
		panic(fmt.Errorf("message loan.v1.Loan does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Loan) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "loan.v1.Loan.principal":
		if x.Principal == nil {
			x.Principal = new(v1beta1.Coin)
		}
		return protoreflect.ValueOfMessage(x.Principal.ProtoReflect())
	case "loan.v1.Loan.outstanding":
		if x.Outstanding == nil {
			x.Outstanding = new(v1beta1.Coin)
		}
		return protoreflect.ValueOfMessage(x.Outstanding.ProtoReflect())
	case "loan.v1.Loan.created_at":
		if x.CreatedAt == nil {
			x.CreatedAt = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.CreatedAt.ProtoReflect())
	case "loan.v1.Loan.approved_at":
		if x.ApprovedAt == nil {
			x.ApprovedAt = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.ApprovedAt.ProtoReflect())
	case "loan.v1.Loan.disbursed_at":
		if x.DisbursedAt == nil {
			x.DisbursedAt = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.DisbursedAt.ProtoReflect())
	case "loan.v1.Loan.id":
		panic(fmt.Errorf("field id of message loan.v1.Loan is not mutable"))
	case "loan.v1.Loan.borrower":
		panic(fmt.Errorf("field borrower of message loan.v1.Loan is not mutable"))
	case "loan.v1.Loan.laz_policy":
		panic(fmt.Errorf("field laz_policy of message loan.v1.Loan is not mutable"))
	case "loan.v1.Loan.tenor_months":
		panic(fmt.Errorf("field tenor_months of message loan.v1.Loan is not mutable"))
	case "loan.v1.Loan.status":
		panic(fmt.Errorf("field status of message loan.v1.Loan is not mutable"))
	case "loan.v1.Loan.metadata_hash":
		panic(fmt.Errorf("field metadata_hash of message loan.v1.Loan is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: loan.v1.Loan"))
		}
		panic(fmt.Errorf("message loan.v1.Loan does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Loan) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "loan.v1.Loan.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "loan.v1.Loan.borrower":
		return protoreflect.ValueOfString("")
	case "loan.v1.Loan.laz_policy":
		return protoreflect.ValueOfString("")
	case "loan.v1.Loan.principal":
		m := new(v1beta1.Coin)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "loan.v1.Loan.outstanding":
		m := new(v1beta1.Coin)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "loan.v1.Loan.tenor_months":
		return protoreflect.ValueOfUint64(uint64(0))
	case "loan.v1.Loan.status":
		return protoreflect.ValueOfEnum(0)
	case "loan.v1.Loan.created_at":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "loan.v1.Loan.approved_at":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "loan.v1.Loan.disbursed_at":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "loan.v1.Loan.metadata_hash":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: loan.v1.Loan"))
		}
		panic(fmt.Errorf("message loan.v1.Loan does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Loan) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in loan.v1.Loan", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Loan) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Loan) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Loan) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Loan) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Loan)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Borrower)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.LazPolicy)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Principal != nil {
			l = options.Size(x.Principal)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Outstanding != nil {
			l = options.Size(x.Outstanding)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.TenorMonths != 0 {
			n += 1 + runtime.Sov(uint64(x.TenorMonths))
		}
		if x.Status != 0 {
			n += 1 + runtime.Sov(uint64(x.Status))
		}
		if x.CreatedAt != nil {
			l = options.Size(x.CreatedAt)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.ApprovedAt != nil {
			l = options.Size(x.ApprovedAt)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.DisbursedAt != nil {
			l = options.Size(x.DisbursedAt)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MetadataHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Loan)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.MetadataHash) > 0 {
			i -= len(x.MetadataHash)
			copy(dAtA[i:], x.MetadataHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MetadataHash)))
			i--
			dAtA[i] = 0x5a
		}
		if x.DisbursedAt != nil {
			encoded, err := options.Marshal(x.DisbursedAt)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x52
		}
		if x.ApprovedAt != nil {
			encoded, err := options.Marshal(x.ApprovedAt)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x4a
		}
		if x.CreatedAt != nil {
			encoded, err := options.Marshal(x.CreatedAt)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x42
		}
		if x.Status != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Status))
			i--
			dAtA[i] = 0x38
		}
		if x.TenorMonths != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TenorMonths))
			i--
			dAtA[i] = 0x30
		}
		if x.Outstanding != nil {
			encoded, err := options.Marshal(x.Outstanding)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x2a
		}
		if x.Principal != nil {
			encoded, err := options.Marshal(x.Principal)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.LazPolicy) > 0 {
			i -= len(x.LazPolicy)
			copy(dAtA[i:], x.LazPolicy)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LazPolicy)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Borrower) > 0 {
			i -= len(x.Borrower)
			copy(dAtA[i:], x.Borrower)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Borrower)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Loan)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Loan: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Loan: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Borrower = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LazPolicy", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LazPolicy = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Principal == nil {
					x.Principal = &v1beta1.Coin{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Principal); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Outstanding", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Outstanding == nil {
					x.Outstanding = &v1beta1.Coin{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Outstanding); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TenorMonths", wireType)
				}
				x.TenorMonths = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TenorMonths |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				x.Status = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Status |= LoanStatus(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.CreatedAt == nil {
					x.CreatedAt = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.CreatedAt); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ApprovedAt", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.ApprovedAt == nil {
					x.ApprovedAt = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.ApprovedAt); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DisbursedAt", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.DisbursedAt == nil {
					x.DisbursedAt = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.DisbursedAt); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MetadataHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MetadataHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: overloan/loan/v1/loan.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoanStatus int32

const (
	LoanStatus_LOAN_STATUS_UNSFECIFIED LoanStatus = 0
	LoanStatus_LOAN_STATUS_PENDING     LoanStatus = 1
	LoanStatus_LOAN_STATUS_APPROVED    LoanStatus = 2
	LoanStatus_LOAN_STATUS_DISBURSED   LoanStatus = 3
	LoanStatus_LOAN_STATUS_REJECTED    LoanStatus = 4
	LoanStatus_LOAN_STATUS_CANCELLED   LoanStatus = 5
)

// Enum value maps for LoanStatus.
var (
	LoanStatus_name = map[int32]string{
		0: "LOAN_STATUS_UNSFECIFIED",
		1: "LOAN_STATUS_PENDING",
		2: "LOAN_STATUS_APPROVED",
		3: "LOAN_STATUS_DISBURSED",
		4: "LOAN_STATUS_REJECTED",
		5: "LOAN_STATUS_CANCELLED",
	}
	LoanStatus_value = map[string]int32{
		"LOAN_STATUS_UNSFECIFIED": 0,
		"LOAN_STATUS_PENDING":     1,
		"LOAN_STATUS_APPROVED":    2,
		"LOAN_STATUS_DISBURSED":   3,
		"LOAN_STATUS_REJECTED":    4,
		"LOAN_STATUS_CANCELLED":   5,
	}
)

func (x LoanStatus) Enum() *LoanStatus {
	p := new(LoanStatus)
	*p = x
	return p
}

func (x LoanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_overloan_loan_v1_loan_proto_enumTypes[0].Descriptor()
}

func (LoanStatus) Type() protoreflect.EnumType {
	return &file_overloan_loan_v1_loan_proto_enumTypes[0]
}

func (x LoanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoanStatus.Descriptor instead.
func (LoanStatus) EnumDescriptor() ([]byte, []int) {
	return file_overloan_loan_v1_loan_proto_rawDescGZIP(), []int{0}
}

type Loan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// sdk.AccAddress (bech32)
	Borrower string `protobuf:"bytes,2,opt,name=borrower,proto3" json:"borrower,omitempty"`
	// group policy address yang approve
	// audit siapa policy yang approve
	LazPolicy string `protobuf:"bytes,3,opt,name=laz_policy,json=lazPolicy,proto3" json:"laz_policy,omitempty"`
	// Nilai pokok awal peminjaman
	Principal *v1beta1.Coin `protobuf:"bytes,4,opt,name=principal,proto3" json:"principal,omitempty"`
	// Sisa kewajiban bayar saat ini
	Outstanding *v1beta1.Coin `protobuf:"bytes,5,opt,name=outstanding,proto3" json:"outstanding,omitempty"`
	// Durasi pinjaman dalam bulan
	TenorMonths uint64 `protobuf:"varint,6,opt,name=tenor_months,json=tenorMonths,proto3" json:"tenor_months,omitempty"`
	// status pembayaran
	Status      LoanStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=loan.v1.LoanStatus" json:"status,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ApprovedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	DisbursedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=disbursed_at,json=disbursedAt,proto3" json:"disbursed_at,omitempty"`
	// document hash (bisa pakai hash dari IPFS kalau digunakan)
	MetadataHash string `protobuf:"bytes,11,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
}

func (x *Loan) Reset() {
	*x = Loan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overloan_loan_v1_loan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_overloan_loan_v1_loan_proto_rawDescGZIP(), []int{0}
}

func (x *Loan) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Loan) GetBorrower() string {
	if x != nil {
		return x.Borrower
	}
	return ""
}

func (x *Loan) GetLazPolicy() string {
	if x != nil {
		return x.LazPolicy
	}
	return ""
}

func (x *Loan) GetPrincipal() *v1beta1.Coin {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *Loan) GetOutstanding() *v1beta1.Coin {
	if x != nil {
		return x.Outstanding
	}
	return nil
}

func (x *Loan) GetTenorMonths() uint64 {
	if x != nil {
		return x.TenorMonths
	}
	return 0
}

func (x *Loan) GetStatus() LoanStatus {
	if x != nil {
		return x.Status
	}
	return LoanStatus_LOAN_STATUS_UNSFECIFIED
}

func (x *Loan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Loan) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *Loan) GetDisbursedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisbursedAt
	}
	return nil
}

func (x *Loan) GetMetadataHash() string {
	if x != nil {
		return x.MetadataHash
	}
	return ""
}

var File_overloan_loan_v1_loan_proto protoreflect.FileDescriptor

var file_overloan_loan_v1_loan_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x61, 0x6e, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2f,
	0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c,
	0x6f, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x03, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x61, 0x7a, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6c, 0x61, 0x7a, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x37, 0x0a, 0x09, 0x70,
	0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63,
	0x69, 0x70, 0x61, 0x6c, 0x12, 0x3b, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x73, 0x74, 0x61, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x43, 0x6f, 0x69, 0x6e, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x6e, 0x6f, 0x72, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x65, 0x6e, 0x6f, 0x72, 0x4d, 0x6f,
	0x6e, 0x74, 0x68, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x6f, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3b, 0x0a, 0x0b,
	0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x62, 0x75, 0x72, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x64, 0x69, 0x73,
	0x62, 0x75, 0x72, 0x73, 0x65, 0x64, 0x41, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x2a, 0xac, 0x01,
	0x0a, 0x0a, 0x4c, 0x6f, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17,
	0x4c, 0x4f, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x46,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x4f, 0x41,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x4f, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15,
	0x4c, 0x4f, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x49, 0x53, 0x42,
	0x55, 0x52, 0x53, 0x45, 0x44, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x4f, 0x41, 0x4e, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10,
	0x04, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x4f, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x42, 0x7f, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x4c, 0x6f, 0x61,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x28, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x6c,
	0x6f, 0x61, 0x6e, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x6c, 0x6f, 0x61, 0x6e,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x4c, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x4c, 0x6f, 0x61, 0x6e, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x07, 0x4c, 0x6f, 0x61, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x13, 0x4c,
	0x6f, 0x61, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x08, 0x4c, 0x6f, 0x61, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_overloan_loan_v1_loan_proto_rawDescOnce sync.Once
	file_overloan_loan_v1_loan_proto_rawDescData = file_overloan_loan_v1_loan_proto_rawDesc
)

func file_overloan_loan_v1_loan_proto_rawDescGZIP() []byte {
	file_overloan_loan_v1_loan_proto_rawDescOnce.Do(func() {
		file_overloan_loan_v1_loan_proto_rawDescData = protoimpl.X.CompressGZIP(file_overloan_loan_v1_loan_proto_rawDescData)
	})
	return file_overloan_loan_v1_loan_proto_rawDescData
}

var file_overloan_loan_v1_loan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_overloan_loan_v1_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_overloan_loan_v1_loan_proto_goTypes = []interface{}{
	(LoanStatus)(0),               // 0: loan.v1.LoanStatus
	(*Loan)(nil),                  // 1: loan.v1.Loan
	(*v1beta1.Coin)(nil),          // 2: cosmos.base.v1beta1.Coin
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_overloan_loan_v1_loan_proto_depIdxs = []int32{
	2, // 0: loan.v1.Loan.principal:type_name -> cosmos.base.v1beta1.Coin
	2, // 1: loan.v1.Loan.outstanding:type_name -> cosmos.base.v1beta1.Coin
	0, // 2: loan.v1.Loan.status:type_name -> loan.v1.LoanStatus
	3, // 3: loan.v1.Loan.created_at:type_name -> google.protobuf.Timestamp
	3, // 4: loan.v1.Loan.approved_at:type_name -> google.protobuf.Timestamp
	3, // 5: loan.v1.Loan.disbursed_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_overloan_loan_v1_loan_proto_init() }
func file_overloan_loan_v1_loan_proto_init() {
	if File_overloan_loan_v1_loan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_overloan_loan_v1_loan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Loan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_overloan_loan_v1_loan_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_overloan_loan_v1_loan_proto_goTypes,
		DependencyIndexes: file_overloan_loan_v1_loan_proto_depIdxs,
		EnumInfos:         file_overloan_loan_v1_loan_proto_enumTypes,
		MessageInfos:      file_overloan_loan_v1_loan_proto_msgTypes,
	}.Build()
	File_overloan_loan_v1_loan_proto = out.File
	file_overloan_loan_v1_loan_proto_rawDesc = nil
	file_overloan_loan_v1_loan_proto_goTypes = nil
	file_overloan_loan_v1_loan_proto_depIdxs = nil
}
